#! /bin/bash
AS_LINK="`echo \"$*\" | grep 'as-new'`"
LD_LINK="`echo \"$*\" | grep 'ld-new'`"
LINK="`echo -n "$AS_LINK""$LD_LINK"`"
if [ -n "$LINK" ]; then
	LD_ARGS="`echo \" $*\" | \
		sed 's/ -O[^ ]*//g' | \
		sed 's/ -W[^ ]*//g' | \
		sed 's/ -g//g' | \
		sed 's/ -l[^ ]*//g' | \
		sed 's/ [ ]*/ /g'`"
	ld $LD_ARGS
else
	CONFTEST="`echo \"$*\" | grep ' conftest '`"
	if [ -n "$CONFTEST" ]; then
		LFLAGS="-Xlinker -z -Xlinker muldefs"
		echo '/usr/local/cross/ia32/bin/i686-pc-linux-gnu-gcc' "$@" ' -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/posix -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/ -I/home/pratik/helenos/uspace/app/binutils/../../lib/c/include -imacros /home/pratik/helenos/uspace/app/binutils/../../../config.h -fexec-charset=UTF-8 -fwide-exec-charset=UTF-32LE -finput-charset=UTF-8 -ffreestanding -fno-builtin -nostdlib -nostdinc -std=gnu99 -D__LE__ -march=pentium -fno-omit-frame-pointer  -T /home/pratik/helenos/uspace/app/binutils/../../lib/c/arch/ia32/_link.ld' "$LFLAGS" '/home/pratik/helenos/uspace/app/binutils/../../lib/posix/libposix.a /home/pratik/helenos/uspace/app/binutils/../../lib/c/libc.a /home/pratik/helenos/uspace/app/binutils/../../lib/softint/libsoftint.a /home/pratik/helenos/uspace/app/binutils/../../lib/softfloat/libsoftfloat.a /home/pratik/helenos/uspace/app/binutils/confobj.o'
		/usr/local/cross/ia32/bin/i686-pc-linux-gnu-gcc $@  -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/posix -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/ -I/home/pratik/helenos/uspace/app/binutils/../../lib/c/include -imacros /home/pratik/helenos/uspace/app/binutils/../../../config.h -fexec-charset=UTF-8 -fwide-exec-charset=UTF-32LE -finput-charset=UTF-8 -ffreestanding -fno-builtin -nostdlib -nostdinc -std=gnu99 -D__LE__ -march=pentium -fno-omit-frame-pointer  -T /home/pratik/helenos/uspace/app/binutils/../../lib/c/arch/ia32/_link.ld $LFLAGS /home/pratik/helenos/uspace/app/binutils/../../lib/posix/libposix.a /home/pratik/helenos/uspace/app/binutils/../../lib/c/libc.a /home/pratik/helenos/uspace/app/binutils/../../lib/softint/libsoftint.a /home/pratik/helenos/uspace/app/binutils/../../lib/softfloat/libsoftfloat.a /home/pratik/helenos/uspace/app/binutils/confobj.o
	else
		GCC_ARGS="`echo \" $*\" | \
			sed 's/ -Werror//g' | \
			sed 's/ -Wc++-compat//g' | \
			sed 's/ [ ]*/ /g'`"
		echo '/usr/local/cross/ia32/bin/i686-pc-linux-gnu-gcc' "$GCC_ARGS" ' -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/posix -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/ -I/home/pratik/helenos/uspace/app/binutils/../../lib/c/include -imacros /home/pratik/helenos/uspace/app/binutils/../../../config.h -fexec-charset=UTF-8 -fwide-exec-charset=UTF-32LE -finput-charset=UTF-8 -ffreestanding -fno-builtin -nostdlib -nostdinc -std=gnu99 -D__LE__ -march=pentium -fno-omit-frame-pointer '
		/usr/local/cross/ia32/bin/i686-pc-linux-gnu-gcc $GCC_ARGS  -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/posix -I/home/pratik/helenos/uspace/app/binutils/../../lib/posix/include/ -I/home/pratik/helenos/uspace/app/binutils/../../lib/c/include -imacros /home/pratik/helenos/uspace/app/binutils/../../../config.h -fexec-charset=UTF-8 -fwide-exec-charset=UTF-32LE -finput-charset=UTF-8 -ffreestanding -fno-builtin -nostdlib -nostdinc -std=gnu99 -D__LE__ -march=pentium -fno-omit-frame-pointer 
	fi
fi
